"""initial schema

Revision ID: 3e7131feb86b
Revises: 
Create Date: 2026-07-14 19:43:24.712348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e7131feb86b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('fiscal_year_start', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gl_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('product_line', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('headcount_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=True),
    sa.Column('total_compensation', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('new_hires', sa.Integer(), nullable=True),
    sa.Column('departures', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_pipeline',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('deal_name', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('expected_close_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actuals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_lines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentary_drafts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_run_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_lines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_run_id', sa.String(), nullable=True),
    sa.Column('checkpoint', sa.String(), nullable=True),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_run_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assumptions_json', sa.JSON(), nullable=True),
    sa.Column('revenue_impact', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ebitda_impact', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_impact', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('probability', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trial_balance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_run_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('variance_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('variance_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_material', sa.Boolean(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('root_causes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('variance_id', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('similar_case_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['variance_id'], ['variances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('root_causes')
    op.drop_table('vendor_invoices')
    op.drop_table('variances')
    op.drop_table('trial_balance')
    op.drop_table('scenarios')
    op.drop_table('review_logs')
    op.drop_table('forecast_lines')
    op.drop_table('commentary_drafts')
    op.drop_table('budget_lines')
    op.drop_table('actuals')
    op.drop_table('sales_pipeline')
    op.drop_table('headcount_data')
    op.drop_table('gl_accounts')
    op.drop_table('agent_runs')
    op.drop_table('entities')
    # ### end Alembic commands ###
