"""P6-05 investigation verdict and proposal engine (re-exports only)."""

from finance.investigation.proposal import (
    AmountTransform,
    ResolutionProposal,
    assemble_verdict,
    bind_proposal_amount,
    proposal_hash,
    quarantine_llm_shaped,
    sanitise_llm_text,
    satisfies_d3_gate,
)
from finance.investigation.verdict import (
    NON_CAUSAL_BANNER,
    AuthorizedAction,
    CausalConclusion,
    Confidence,
    Correlation,
    FactualFinding,
    Hypothesis,
    InvestigationVerdict,
    assert_no_preauthorized,
    check_no_causal_text,
    new_fingerprint,
    refuse_hypothesis_as_fact,
    refuse_promotion,
    verdict_canonical_bytes,
    verdict_handoff,
)

__all__ = [
    "NON_CAUSAL_BANNER",
    "AmountTransform",
    "AuthorizedAction",
    "CausalConclusion",
    "Confidence",
    "Correlation",
    "FactualFinding",
    "Hypothesis",
    "InvestigationVerdict",
    "ResolutionProposal",
    "assemble_verdict",
    "assert_no_preauthorized",
    "bind_proposal_amount",
    "check_no_causal_text",
    "new_fingerprint",
    "proposal_hash",
    "quarantine_llm_shaped",
    "refuse_hypothesis_as_fact",
    "refuse_promotion",
    "sanitise_llm_text",
    "satisfies_d3_gate",
    "verdict_canonical_bytes",
    "verdict_handoff",
]
