"""P6-08 track B verification surface: minter, registry, replay, audit, clock."""

from finance.verification.audit import AuditEntry, AuditLog, digest_handoff, hash_report
from finance.verification.clock import FUTURE_SKEW_BUDGET, assess_clock
from finance.verification.minter import MintRefused, mint_report
from finance.verification.orchestrator import (
    R1Observation,
    R2Observation,
    R3Observation,
    ReaderFailed,
    VerificationRefused,
    verify_execution,
)
from finance.verification.reason_codes import (
    FAILED_CODES,
    INCOMPLETE_CODES,
    REASON_REGISTRY,
    VERIFY_BATCH_SKEW,
    VERIFY_CASE_SKEW,
    VERIFY_CLOCK_SKEW,
    VERIFY_CONTROL_SKEW,
    VERIFY_COUNT_SKEW,
    VERIFY_DIGEST_MISMATCH,
    VERIFY_DOUBLE_MINT_REFUSED,
    VERIFY_HANDOFF_CORRUPT,
    VERIFY_PREFIX_ESCAPE,
    VERIFY_RESULT_MISSING,
    VERIFY_RESULT_MUTATED,
    VERIFY_STALE_REPLAY,
    VERIFY_TOLERANCE_EXCEEDED,
    VERIFY_UNAUTHORIZED_EXECUTION,
    is_registered,
    require_failed_code,
    require_registered,
)
from finance.verification.replay import ReplayStore

__all__ = [
    "FAILED_CODES",
    "FUTURE_SKEW_BUDGET",
    "INCOMPLETE_CODES",
    "REASON_REGISTRY",
    "R1Observation",
    "R2Observation",
    "R3Observation",
    "AuditEntry",
    "AuditLog",
    "MintRefused",
    "ReaderFailed",
    "ReplayStore",
    "VerificationRefused",
    "VERIFY_BATCH_SKEW",
    "VERIFY_CASE_SKEW",
    "VERIFY_CLOCK_SKEW",
    "VERIFY_CONTROL_SKEW",
    "VERIFY_COUNT_SKEW",
    "VERIFY_DIGEST_MISMATCH",
    "VERIFY_DOUBLE_MINT_REFUSED",
    "VERIFY_HANDOFF_CORRUPT",
    "VERIFY_PREFIX_ESCAPE",
    "VERIFY_RESULT_MISSING",
    "VERIFY_RESULT_MUTATED",
    "VERIFY_STALE_REPLAY",
    "VERIFY_TOLERANCE_EXCEEDED",
    "VERIFY_UNAUTHORIZED_EXECUTION",
    "assess_clock",
    "digest_handoff",
    "hash_report",
    "is_registered",
    "mint_report",
    "require_failed_code",
    "require_registered",
    "verify_execution",
]
